### ISSUE TITLE
Full namespace references

### ISSUE THREAD

**Issue by Solinx** [eusonlito/laravel-Gettext#1]
Hello Lito,

This package is quite nifty. Unfortunately we ran into some issues due to the namespacing used in the GettextServiceProvider. 

Could you use 
"use Illuminate\Support\Facades\App;"
"use Illuminate\Support\Facades\Input;"

instead of just 
"use App;"
"use Input;"

Thanks!

**Comment by eusonlito** [comment]
Done, updated to release `v1.1.2`.

**Comment by Solinx** [comment]
Thanks!
