### ISSUE TITLE
Locale in URL

### ISSUE THREAD

**Issue by ivandokov** [eusonlito/laravel-Gettext#3]
The library is just great, there is only one missing part - option to set the locale in the URL

```
example.com/en_us/...
example.com/en/...
example.com/bg_bg/...
example.com/bg/...
```

This will resolve the issue with different content for the same pages.
Also in some cases you may not want to create a cookie.

You can take a look at this package https://github.com/Anahkiasen/polyglot
It handles the locale from the URL, Route groups with locale prefix and URL generation functions to include the locale.

**Comment by eusonlito** [comment]
What about a rewrite rule to apache?:

```
RewriteRule ^/(.+?)/(.*)$  $2?lang=$1 [L]
```

**Comment by ivandokov** [comment]
I don't think this should be implemented on a hosting level. It should be in the code.

**Comment by eusonlito** [comment]
I think that there are too many possibilities to implement in the code, for example set language into a subdomain: `en.example.com`. rewrite rules are easy to implement and you can cover your needs.

Anyway, I will check my code to find a flexible solution.

**Comment by ivandokov** [comment]
You can take a look at the implementation in the package which I linked above. It's really well coded, but kinda abandoned after Laravel 5.

**Comment by ivandokov** [comment]
Any news/ideas? If you need help I'd like to join, because this feature is important for me and I think it will be useful for everyone.

**Comment by eusonlito** [comment]
Hello, sorry, I'm now very busy with two projects.

You can do a fork and implement the changes. I will try to update the package in 1 or 2 weeks.

Regards.
